### ISSUE TITLE
Update mode documentation to recommend GUIDED/AUTO

### ISSUE THREAD

**Issue by hamishwillee** [diydrones/dronekit-python#119]
Update [VehicleMode](http://python.dronekit.io/automodule.html#droneapi.lib.VehicleMode) reference to *recommend* AUTO and GUIDED modes. 

At the moment we don't really comment on this other than to point to the supported modes. In practice though you really shouldn't be using dronekit within a manual mode (which may *require* a transmitter) unless you know what you're doing. These modes are supported on all platforms and are known to be safe. 

@mrpollo Seem reasonable?

**Comment by mrpollo** [comment]
:+1:
