### ISSUE TITLE
Build seems to have reverted to old reference and theme

### ISSUE THREAD

**Issue by hamishwillee** [diydrones/dronekit-python#136]
The build isn't right after #124 - unrelated to that particular push though.
See http://python.dronekit.io/automodule.html - this is the old API reference (like months!)

Also there are big spaces above the level 2 headings, which were removed by current theme.

Something not right!

**Comment by tcr3dr** [comment]
@hamishwillee Can you confirm this is an issue? I want to know if this is something I can dig into.

**Comment by hamishwillee** [comment]
@tcr3dr Not an issue right now so I will close. It reverted a few times in the past but @mrpollo did some changes which may have fixed it. If this occurs again I'll open a generic issue about the fact it keeps reverting.

**Comment by tcr3dr** [comment]
@hamishwillee Sounds good. I'll be able to help "in the moment" fix it if this comes up.
