### ISSUE TITLE
Fix layout of loading API

### ISSUE THREAD

**Issue by hamishwillee** [diydrones/dronekit-python#153]
In [Getting Started](http://python.dronekit.io/guide/getting_started.html)

![image](https://cloud.githubusercontent.com/assets/5368500/8049385/07c046c8-0ea2-11e5-9ebc-e25343840eb1.png)

**Comment by hamishwillee** [comment]
@mrpollo The source file here is correct, and so is the HTML. Unfortunately the paragraph is not being rendered:
![image](https://cloud.githubusercontent.com/assets/5368500/8051333/7e67893c-0ebe-11e5-9c24-4b41c4b63cc2.png)

So this is a theme/CSS problem. As I still can't build the theme, handballing to you!

**Comment by zlite** [comment]
Any update on this? Seems nuts that we have to go through backflips to add a carriage return


![getting_started](https://cloud.githubusercontent.com/assets/18071/8114662/fe4109c2-102a-11e5-8ff8-872f2ba335d7.png)

**Comment by mrpollo** [comment]
our great @kaitlynhova is taking a look at this, she has some fixes in place right now and will push once she feels she's got them all sorted, I'll post back with update.

**Comment by hamishwillee** [comment]
@zlite @mrpollo This is now fixed on the live version. Thank you @kaitlynhova
