### ISSUE TITLE
Internal links jump to location one item below intended one

### ISSUE THREAD

**Issue by zlite** [diydrones/dronekit-python#162]
When you click on an internal link, such as the Vehicle Attributes on this page (http://python.dronekit.io/guide/vehicle_state_and_parameters.html), you are actually taken to one past the one you want. I suspect this is due to the navbar obscuring the one it thinks it's jumping to. So we'll need to add an offset to each jump

**Comment by hamishwillee** [comment]
@kaitlynhova - this is a duplicate of https://github.com/3drobotics/sphinx_3dr_theme/issues/21 . Can you please ETA when you might be able to work on it?

**Comment by hamishwillee** [comment]
This is fixed
