### ISSUE TITLE
Math module needs to be a dependency of dronekit

### ISSUE THREAD

**Issue by hamishwillee** [diydrones/dronekit-python#181]
@mrpollo @djnugent I just tried the fix in #174 against our examples. They crashed because math is not defined in the example script. I don't believe that our examples should "have" to import this dependency, which means that you will need to import this in dronekit.

Crash is in the simple_goto.py example (unmodified).

```
if math.isnan(alt) or math.isinf(alt):
NameError: global name 'math' is not defined
```

Of course I could be doing something completely wrong ... in which case "help"!

**Comment by djnugent** [comment]
@hamishwillee You are correct. I made an error with my PR. I will fix it.

**Comment by tcr3dr** [comment]
Confirmed fixed. Added to v1.3.1 release
