### ISSUE TITLE
Broken link on README to the python autodocs

### ISSUE THREAD

**Issue by klinvill** [diydrones/dronekit-python#26]
It looks like updating the name from droneapi-python to dronekit-python may have messed up the gh-pages hosting. I am get a 404 not found message when I try to access the autodocs at either http://diydrones.github.io/droneapi-python/ or http://diydrones.github.io/dronekit-python/ even though the gh-pages branch seems to look ok.

**Comment by geeksville** [comment]
Thanks!  I'll change it back till we figure out what is up!

**Comment by geeksville** [comment]
ok - I've fixed the link to point to the new python.dronekit.io webpage (built from the same sphynx autodocs).  Should be good now (at either dronekit-python or droneapi-python)
