### ISSUE TITLE
Docs: Copyright is Kevin Hester while on Android Docs is 3DRobotics. 

### ISSUE THREAD

**Issue by hamishwillee** [diydrones/dronekit-python#31]
Should the copyrights be the same, and if so, which is correct?

[Python](http://python.dronekit.io/) : © Copyright 2014, Kevin Hester.
[Android](http://android.dronekit.io/): © Copyright 2015, 3D Robotics.

**Comment by phmagic** [comment]
I vote 2015 3D Robotics. What do others think?

**Comment by hamishwillee** [comment]
That would be desirable. 

Legally this depends on how Kevin is employed and his T&Cs. Under my contract anything I do for 3DR would be copyright 3DR but who knows what his says. And of course he might be happy to let us own the copyright.

**Comment by hamishwillee** [comment]
Closing, as issue will be fixed when #44 is merged
