### ISSUE TITLE
Docs: Left alignment of 3DR Logo differs from Android docs

### ISSUE THREAD

**Issue by hamishwillee** [diydrones/dronekit-python#32]
Just toggle between the two sites and you can see the logo move to the left. The Android alignment looks better to me. I am assigning this as a python issue since both sites are built off the same theme.

**Comment by phmagic** [comment]
Hi Hamish, are you talking about the nav bar?

**Comment by kaitlynhova** [comment]
Can you refresh the page? I've been noticing a similar issue but now it looks fixed to me

**Comment by hamishwillee** [comment]
Phu, yes, I am talking about the left aligned "DRONEKIT" link on the nav bar.

Kaitlyn, yes, refreshed the page. The alignment is correct now. I am closing this.

But ... note #39
