### ISSUE TITLE
DOC: Getting Started "pip" dependency incorrect

### ISSUE THREAD

**Issue by hamishwillee** [diydrones/dronekit-python#41]
The [Linux Dependencies here](http://python.dronekit.io/getting_started.html#linux-dependencies) for pip are incorrect:

>sudo apt-get install pip python-numpy python-opencv python-serial python-pyparsing python-wxgtk2.8

this should be "python-pip"

**Comment by mrpollo** [comment]
@hamishwillee is this closed by https://github.com/diydrones/dronekit-python/pull/38 ?

**Comment by mrpollo** [comment]
closed by #38

**Comment by hamishwillee** [comment]
Thanks, yes is fixed!
