### ISSUE TITLE
Provide information and vagrant file on how to contribute to docs?

### ISSUE THREAD

**Issue by hamishwillee** [diydrones/dronekit-python#43]
We should make it easier for people to get started with contributing to the documents. The good news is that *sphinx_3dr_theme* can now be updated from pip, so it is now possible to set up sphinx and build the source without having to modify any files (previously you needed to modify the conf file in order to replace the theme). 

I've written a vagrant script that does this. The proposal is to put this in /docs/ alongside the .rst files. The (windows) workflow would be:

1. Create a fork of this project
1. Clone the fork locally 
1. Navigate to your docs folder and run "vagrant up". This will bring up the VM, add sphinx and the theme, pull the latest code git, then build (call "make html").
1. Users can then modify the files in their windows file system/notepadd++ and cause a new build by running: ```vagrant ssh  -c "cd /vagrant && make html"```
1. They can commit the changes and do other git activities through windows. (or through the VM).

Is this approach desirable? Is the location of the vagrantfile in docs OK? (I think it is, but just checking).

In addition, I propose to update README.md to add information about how to contribute (specifically to the docs, but more generally it would be useful to cover how people can join the project?).

I would do this by adding a new heading "Contributing" near the end with a link "Contributing to the Documentation". That doc would explain how to use the vagrant file etc. 

OK?

**Comment by phmagic** [comment]
Sounds good to me.

**Comment by mrpollo** [comment]
@hamishwillee I'm testing your Vagrantfile, I agree with your comments I'll be pushing a branch with your changes so we can reference that, and commit there instead of offline and sharing

**Comment by mrpollo** [comment]
I created a pull request #45 that contains the Vagrant changes you propose, please let me know if they make sense, if they do please post your other changes to that branch.
