### ISSUE TITLE
Companion Computer menu link is at wrong level should be submenu

### ISSUE THREAD

**Issue by zlite** [diydrones/dronekit-python#48]
That link is should be in the submenu, not a menu header. 

It's now like this:
![welcome_to_dronekit-python s_documentation_](https://cloud.githubusercontent.com/assets/18071/7008902/46e6a812-dc4b-11e4-8e6a-7333db871c9b.png)

It should be as shown here: 
![unnamed](https://cloud.githubusercontent.com/assets/18071/7008929/774c0894-dc4b-11e4-8c12-86aaf7f1bef5.png)

**Comment by mrpollo** [comment]
Agreed, I'll make this change right away.

**Comment by mrpollo** [comment]
@hamishwillee regarding your comments on #46 would you be able to submit a PR with a fix for this taking into consideration @zlite comments?

**Comment by hamishwillee** [comment]
My comments are now no longer relevant given a "pure-Air" focus for the python docs. So no need. This can probably be closed.

**Comment by zlite** [comment]
Now that we've fixed the level of the Companion Computer link, we can remove the second stand-alone top-level link, as shown:
![getting_started](https://cloud.githubusercontent.com/assets/18071/7016710/f7b9caae-dc9e-11e4-8dd8-43a8ca03eaf7.png)

**Comment by hamishwillee** [comment]
This was fixed
