### ISSUE TITLE
test-upload.py is not a dronekit-python example

### ISSUE THREAD

**Issue by hamishwillee** [diydrones/dronekit-python#62]
[test-upload.py](https://github.com/diydrones/dronekit-python/blob/master/example/log_upload/test-upload.py) shows how to upload a file to a service with the Cloud (REST) API, using Python. IMO that makes it something that belongs in the cloud example code, NOT in the dronekit-python example code.

When you've created a place for the cloud docs and issues, I'll move this across (assuming you agree)

**Comment by mrpollo** [comment]
lets remove this example

**Comment by hamishwillee** [comment]
I will delete

**Comment by hamishwillee** [comment]
Closed by #82
