### ISSUE TITLE
Failure for non interactive use

### ISSUE THREAD

**Issue by geeksville** [diydrones/dronekit-python#7]
reported via email:

Is there a way to call  DroneAPI without the interactive MavProxy ?
 
I have MavProxy running in the background and the droneapi.module loaded:
 
screen -d -m -s /bin/bash mavproxy.py --master=/dev/ttyAMA0 --baudrate 57600 --aircraft OCTO8 --out=127.0.0.1:12345 --cmd="module load droneapi.module.api;" > /tmp/rc.log 2>&1
 
If I execute small_demo.py outside of interactive MavProxy it fails on this line:
api = local_connect()
 
I assume that the function would find my local running copy but I guess that is a wrong assumption?
 
Of course it runs fine inside the interactive MavProxy but only after it completes loading ….. so I can’t use the “api start” as a parameter.
Thanks

**Comment by trsk** [comment]
I'm having the same problem. Any solutions or workarounds here?

**Comment by geeksville** [comment]
Oh yes.  This was fixed some time ago.  There is now a --daemon command line parameter I added to mavproxy.  If you use that parameter mavproxy will disconnect from stdin.  cc @mrpollo

**Comment by mrpollo** [comment]
thanks @geeksville.

@hamishwillee can we document this?

**Comment by hamishwillee** [comment]
@mrpollo @geeksville I'd document if I could get it to work. My understanding is that I should be able to run mavproxy from my WinPython command prompt - but when I try the following mavproxy runs as normal
```
mavproxy.py --master=127.0.0.1:14550 --cmd="module load droneapi.module.api; api start C:\Users\hamis_000\Documents\vagranttesting\dronekit-python\examples\simple_goto\simple_goto.py" --daemon
```
Is it that you want to start mavproxy without even a command prompt somehow? If so, how is this done on Windows? If not, why would MavPorxy be running with the above command?
