### ISSUE TITLE
message_factory and send_mavlink(message) docs have incorrect advice

### ISSUE THREAD

**Issue by hamishwillee** [diydrones/dronekit-python#85]
``message_factory`` and ``send_mavlink(message)`` state that custom commands are a catch-all/back door in case we miss something in the API. 

This is incorrect. These are also useful for sending arbitrary commands in guided mode. 

----

In addition, we need guide documentation on these. The documentation should cover that there are a number of ways to send messages. For example COMMAND LONG is a basic message format that can be used to send any seven parameter command. So you could use:
```
vehicle.message_factory.command_long_encode to send a MAV_CMD_CONDITION_YAW 
```

However you could also send this command using its own method like below. The benefit being that you don't have to think about command ids, sequence numbers etc.:

```
vehicle.message_factory.mav_cmd_condition_yaw_encode
```

**Comment by mrpollo** [comment]
:+1: agreed, you are correct

**Comment by hamishwillee** [comment]
See #90 for updates to the API Reference to explain that send_mavlink is useful for sending arbitrary messages, particularly in GUIDED mode. I will leave this open until I create a "Custom commands" page.

**Comment by jsjain007** [comment]
yes you are perfectly correct, now it makes more sense of the documentation
(y)

**Comment by jsjain007** [comment]
:+1:  now it makes more clear how exactly to send commands, docs sure needs to be updated with more examples on sending mavlink messages.

**Comment by hamishwillee** [comment]
@jsjain007 Please don't hang off closed issues - if you have a genuine issue then add the error as a separate case. This is not actually an issue - there are enough examples on the topic, you just have another error. The right place to raise that is the discussion boards: https://discuss.dronekit.io/c/python

I suspect your problem is using an older version of pymavlink which does not include the takeoff command.

**Comment by jsjain007** [comment]
sure

**Comment by FFFgrid** [comment]
May I ask a queston?
When I run 'vehicle.message_factory.mav_cmd_condition_yaw_encode',it shows that vehicle does not have an attribute named message_factory,Why?
