### ISSUE TITLE
GPSInfo   - what values are returned if we can’t get a fix

### ISSUE THREAD

**Issue by hamishwillee** [diydrones/dronekit-python#86]
GPSInfo 

- what values are returned if we can’t get a fix?
- Are all values as in https://pixhawk.ethz.ch/mavlink/#GPS_RAW_INT supported (other docs I see don't have RTK or DGPS options)

The documentation in API Reference currently ignores these points.

**Comment by mrpollo** [comment]
if you have no lock you get ```None``` back

**Comment by hamishwillee** [comment]
Fantastic. Thank you.

**Comment by hamishwillee** [comment]
FYI I updated the ``Vehicle.gps_0`` doc to note that this returns None if there is no lock (#90)
