### ISSUE TITLE
Move/tidy up /example/documentation

### ISSUE THREAD

**Issue by hamishwillee** [diydrones/dronekit-python#93]
The example documentation is currently in two places:

* https://github.com/diydrones/dronekit-python/tree/master/example/documentation
* https://github.com/diydrones/dronekit-python/tree/master/docs/examples

Action is to move the documentation all into the official docs. First step to simply remove the content of migrated docs and add links to where the content is now. When all examples are migrated, then remove the stubs and perhaps just have a readme in root of /master/example/ explaining where the docs are.

@mrpollo - make sense?

**Comment by mrpollo** [comment]
Agreed.

**Comment by hamishwillee** [comment]
This is closed by #96. Note that there are undocumented examples still (e.g. client_sketch.py). I will raise separate issues for those.
